import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Box, Card, Typography } from "@mui/material";
import EmployeeForm from "@/components/EmployeeForm";
import EmployeeTable from "@/components/EmployeeTable";
import { useFetch } from "@/utils/useFetch";

export default function Home() {
  const { data, isPending, setData } = useFetch("getEmployeesUrl");

  return (
    <>
      <Head>
        <title>Benefits Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          flexDirection="column"
        >
          <Typography variant="h4" component="h1" padding={1}>
            Benefits Calculator
          </Typography>
          <Card variant="elevation" sx={{ p: 5 }}>
            <EmployeeForm savedData={data} setData={setData} />
          </Card>
        </Box>
        <EmployeeTable data={data} isLoading={isPending} />
      </main>
    </>
  );
}
